### ISSUE TITLE
Exception in Sheet.row_slice() when one row has less columns than the next row

### ISSUE THREAD

**Issue by sergeyspatar** [DissectMalware/xlrd2#4]
You can make a 2x2 table and leave top right cell (B1) blank. Then the first row will have 1 column and the second row will have 2 columns:

![xls_example](https://user-images.githubusercontent.com/29392547/96030646-1a18d500-0e11-11eb-8550-17867f4015f9.png)

Here is a code snippet. You can use [xlrd2_bug.zip](https://github.com/DissectMalware/xlrd2/files/5380170/xlrd2_bug.zip) for your test. _(GitHub does not allow attaching xls, so I had to make a zip archive)_

```python3
import xlrd2

wb = xlrd2.open_workbook('xlrd2_bug.xls')
ws = wb.sheet_by_index(0)
print('ws.nrows:', ws.nrows)
print('ws.ncols:', ws.ncols)
row = ws.row_slice(0)
```
Output:
```
ws.nrows: 2
ws.ncols: 2
Traceback (most recent call last):
  File "./test_xlrd.py", line 8, in <module>
    row = ws.row_slice(0)
  File "/usr/local/lib/python3.8/dist-packages/xlrd2/sheet.py", line 555, in row_slice
    return [
  File "/usr/local/lib/python3.8/dist-packages/xlrd2/sheet.py", line 556, in <listcomp>
    self.cell(rowx, colx)
  File "/usr/local/lib/python3.8/dist-packages/xlrd2/sheet.py", line 425, in cell
    self._cell_formulas[rowx][colx],
IndexError: list index out of range
```

**Comment by DissectMalware** [comment]
The problem is fixed. Please update from Master.
